# =========================================================
# API GATEWAY
# =========================================================

spring.application.name=API-GATEWAY
server.port=8082


# =========================================================
# EUREKA CLIENT
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8085/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true


# =========================================================
# HOSPITAL SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].id=hospital-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://HOSPITAL-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/hospital/**


# =========================================================
# DEPARTMENT SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[1].id=department-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/department/**


# =========================================================
# DOCTOR SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[2].id=doctor-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/doctor/**


# =========================================================
# MEDICIN SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[3].id=medicin-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://MEDICIN-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/medicin/**


# =========================================================
# ROOM + BED
# =========================================================

spring.cloud.gateway.server.webflux.routes[4].id=room-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://ROOM-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/room/**,/api/bed/**